apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-test-app
  namespace: argocd
spec:
     project: default
     source:
       repoURL: git@github.com:Dokcer-DevLink/DevOps.git
       targetRevision: HEAD
       path: dev
       directory:
         recurse: true
     destination:
       server: https://kubernetes.default.svc
       namespace: default
     syncPolicy:
          syncOptions:
          - CreateNamespace=true
          automated:
            prune: true
            selfHeal: true
